imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: []
  hosts:
    # Paths are based on the active modules, do not include here
    - host: ""

# Set options to Generate a Secret on first install
# It will only run if you install the chart for the first time!
# The following Secrets will be created
# PSONO_SECRET_KEY
# PSONO_ACTIVATION_LINK_SECRET
# PSONO_DB_SECRET
# PSONO_EMAIL_SECRET_SALT
# PSONO_PRIVATE_KEY
# PSONO_PUBLIC_KEY
secrets:
  # Set to false if you have your own secrets.
  # If you have predefined values, you need to mount them in the sections below
  # or define them in the env section
  create: true
  # Set the Name of the generated secrets
  name: "psono-deploy-secrets"

server:
  enabled: true
  replicas: 1
  image:
    repository: psono/psono-server
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: ClusterIP
    port: 10100

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Configuring the server is done via env variables. You can add PSONO_var_name to specify
  # the variables listed here: https://doc.psono.com/admin/installation/install-server-ce.html#installation-with-docker
  env: {}
  extraSecretEnvironmentVars: []
  extraVolumeMounts: []
  extraVolumes: []

  envFiles: []

webclient:
  enabled: true
  replicas: 1
  image:
    repository: psono/psono-client
    pullPolicy: IfNotPresent
    tag: latest

  service:
    port: 10101

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  extraVolumeMounts: []
  extraVolumes: []

database:
  enabled: true
  replicas: 1
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: latest

  service:
    port: 5432

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  persistence:
    enabled: false
    storageClass: "-"
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  env:
    []
    # POSTGRES_PASSWORD:
    # POSTGRES_PASSWORD_FILE:
    # POSTGRES_USER: psono
    # POSTGRES_DB: psono

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraSecretEnvironmentVars: []
  extraVolumeMounts: []
  extraVolumes: []

adminClient:
  enabled: true
  replicas: 1
  image:
    repository: psono/psono-admin-client
    pullPolicy: IfNotPresent
    tag: latest

  service:
    port: 10102

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  extraVolumeMounts: []
  extraVolumes: []

mail:
  enabled: false

backup:
  enabled: false
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

  schedule: "00 6 * * *"
  startingDeadlineSeconds: 100
  restartPolicy: OnFailure

  envFiles: []
  env:
    {}
    # BACKUP_TARGET:
    # POSTGRES_USER:
    # POSTGRES_DB:
    # POSTGRES_PASSWORD:
    # POSTGRES_HOST:

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraSecretEnvironmentVars: []
  extraVolumeMounts: []
  extraVolumes: []

  serviceAccount:
    create: true
    annotations: {}
    name: ""
