{{- if .Values.adminClient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adminClient.fullname" . }}
  labels:
    {{- include "adminClient.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "adminClient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "adminClient.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adminClient.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.adminClient.image.repository }}:{{ .Values.adminClient.image.tag }}"
          imagePullPolicy: {{ .Values.adminClient.image.pullPolicy }}
          command:
            - sh
            - -c
            - cp /config/config.json /usr/share/nginx/html/config.json && nginx -g "daemon off;"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.adminClient.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
          {{- if .Values.adminClient.extraVolumeMounts }}
            {{ toYaml .Values.adminClient.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.adminClient.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminClient.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "webclient.fullname" . }}
      {{- if .Values.adminClient.extraVolumes }}
        {{ toYaml .Values.adminClient.extraVolumes | nindent 8}}
      {{- end }}
{{- end }}