{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.webclient.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webclient.fullname" . }}
  labels:
    {{- include "webclient.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webclient.service.type }}
  ports:
    - port: {{ .Values.webclient.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webclient.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.adminClient.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminClient.fullname" . }}
  labels:
    {{- include "adminClient.labels" . | nindent 4 }}
spec:
  type: {{ .Values.adminClient.service.type }}
  ports:
    - port: {{ .Values.adminClient.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adminClient.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
{{- end }}